name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64,arm'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TARGET_PLATFORM: linux/arm/v8
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/submod:latest
    
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/submod
